### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by mac40** [FabianLauer/chrome-vs-code#15]
since this repo can't be found (this or i'm completely blind 😂) in the built-in vs-code extention market it would be nice to have an installation guide in the README.md 😄

**Comment by FabianLauer** [comment]
Hey, please see #14 for installation and #1 for build instructions.

**Comment by mac40** [comment]
my bad 🙈 ...nice work bud

**Comment by FabianLauer** [comment]
No worries :-)
