### ISSUE TITLE
NoSuchBucket and possible depreciation

### ISSUE THREAD

**Issue by ThePixelGamer** [FabianLauer/chrome-vs-code#22]
http://emulator101.com

![image](https://user-images.githubusercontent.com/15077848/54897323-ed4f4680-4e95-11e9-813d-57a03484bc76.png)
"404 Not Found
Code: NoSuchBucket
Message: The specified bucket does not exist
BucketName: emulator101.com
RequestId: FAA826CB4D6B4726
HostId: uY4w8ZWaEr+Osd/rnFRhqAQQ24CZV1CrxPYl0VvDSZ3GeHx/du1Eu4ta4vHxWKLq+mgAAoUoCWg="

![image](https://user-images.githubusercontent.com/15077848/54897341-01934380-4e96-11e9-9524-8dcfb51d1a27.png)

Other than that great work, it's been pretty good to use.

**Comment by FabianLauer** [comment]
Thanks for the reports. I understand these 2 things are unrelated, could you please use a separate issues to report them? Makes it easier to keep track.
Thanks 👍
