### ISSUE TITLE
What's the point?

### ISSUE THREAD

**Issue by TheBrenny** [FabianLauer/chrome-vs-code#8]
So with such a confronting title question, let me start off by saying wicked extensions! You've literally saved my life! #ReferencingDocsWithLightningSpeed! Hats off to you! 🍻

But, back to the point... 😅 I've been flicking through for the last hour trying to figure out how this whole thing works, and after a lazy attempt to trace from the start, I decided to trace from the back and found out that you're loading [`about://home`](https://github.com/FabianLauer/chrome-vs-code/blob/master/src/static/about/home.html) and then redirecting to the correct page from there. I've gotta ask... why? Why can't we just replace all references to `about://home` with [`config.home`](https://github.com/FabianLauer/chrome-vs-code/blob/master/src/static/about/home.html#L6-L12)?

I've got it working without (*well... not quite without...) issues. And perhaps opening this up could be the beginning of right+click and 'Search Google for "potatoes"'?

So long story (3.5hrs worth) short, why not replace `about://home` with `config.home`?

**Comment by FabianLauer** [comment]
Glad you like the extension. Keep in mind it's very much experimental 😇 
I see a few questions here, let me try to answer them.

#### Search Google feature
> And perhaps opening this up could be the beginning of right+click and 'Search Google for "potatoes"'

Please open a separate issue for this so we can track it as a feature request. Thanks!

#### Understanding the Codebase
> ... after a lazy attempt to trace from the start ...

This diagram [could help](https://github.com/FabianLauer/chrome-vs-code/blob/master/docs/diagrams/png/Browser__Basic%20Architecture_0.png). Quite old, maybe not fully up to date, but it should give you an idea of the codebase.

#### `about://home` vs `config.home`

Like in some [other browsers](https://en.wikipedia.org/wiki/About_URI_scheme), the only job of the `about://home` page is to display the user's home page. Actually, `about://home` is the only part of the codebase that should concern itself with determining what the user's actual home page is. It does it like this:
https://github.com/FabianLauer/chrome-vs-code/blob/5bfb83c2287e3bcb02db04bfb21c8342a68af142/src/static/about/home.html#L11

For this reason, the implementation of `about://home` is the only part of the code that actually consumes the value of `config.home` (there's other files in the codebase were `config.home` is referenced, but only for updating config variables, not reading them).

Consider `about://home` as a sign of the [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle).

This makes sending users to the home page very simple. For example:
https://github.com/FabianLauer/chrome-vs-code/blob/ae0e7c4e5dc75672ab8280fc8769bb50c4534626/src/client/BrowserWindow.ts#L53-L55

Sidenote: Browse to `about://index` to see a list of all `about://` pages.

Closing this issue now - hope this answers your questions. Feel free to keep discussing here though.
